EPROD-417 added checked_div and checked_mul to U256
bitfinity-network/bitfinity-evm-sdk pull request #13
Opened 2023-06-29 07:51 UTC by veeso

# Add Support for non-legacy transactions

## Checklist before requesting a review

### Code conventions

- [x] I have performed a self-review of my code
- [x] Every new function is documented
- [x] Object names are auto explicative

### Security

- [x] The PR does not break APIs backward compatibility
- [x] The PR does not break the stable storage backward compatibility

### Testing

- [x] Every function is properly unit tested
- [x] I have added integration tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] IC endpoints are always tested through the `canister_call!` macro

2023-06-29 08:43 UTC, ufoscout requested changes

2023-06-29 08:43 UTC, ufoscout commented on src/did/src/integer.rs
> +    Debug, Default, Clone, Copy, Eq, PartialEq, PartialOrd, Ord, Serialize, Deserialize, Hash,
We explicitly wanted to avoid `copy` here

2023-06-29 08:43 UTC, ufoscout commented on src/did/src/block.rs
> +pub fn calculate_next_block_base_fee(
add tests for:
- "normal" values
- edge cases
- overflows

2023-06-29 11:51 UTC, itsyaasir approved these changes

2023-06-30 10:18 UTC, ufoscout approved these changes

2023-06-30 11:26 UTC, merged