Add option not to fetch blocks
bitfinity-network/bitfinity-evm-sdk pull request #131
Opened 2024-02-19 14:12 UTC by GraDKh

# Issue ticket

Issue ticket link: <>

## Checklist before requesting a review

### Code conventions

- [ ] I have performed a self-review of my code
- [ ] Every new function is documented
- [ ] Object names are auto explicative

### Security

- [ ] The PR does not break APIs backward compatibility
- [ ] The PR does not break the stable storage backward compatibility

### Testing

- [ ] Every function is properly unit tested
- [ ] I have added integration tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] IC endpoints are always tested through the `canister_call!` macro

2024-02-19 14:15 UTC, ufoscout requested changes

2024-02-19 14:15 UTC, ufoscout commented on src/evm-block-extractor/src/main.rs
> +    if !config.remote_rpc_url.is_empty() {
Add a warn message

2024-02-19 14:38 UTC, ufoscout approved these changes

2024-02-20 08:36 UTC, GraDKh commented on src/evm-block-extractor/src/config.rs
> +    #[arg(long = "rpc-url", short('u'), default_value = "")]
Changed to option

2024-02-20 10:17 UTC, F3kilo approved these changes

2024-02-20 16:35 UTC, merged