chore:  accept both input and data for estimating gas
bitfinity-network/bitfinity-evm-sdk pull request #180
Opened 2024-06-21 08:14 UTC by itsyaasir

# Issue ticket

Issue ticket link: <>

## Checklist before requesting a review

### Code conventions

- [x] I have performed a self-review of my code
- [x] Every new function is documented
- [x] Object names are auto explicative

### Security

- [x] The PR does not break APIs backward compatibility
- [x] The PR does not break the stable storage backward compatibility

### Testing

- [x] Every function is properly unit tested
- [x] I have added integration tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] IC endpoints are always tested through the `canister_call!` macro

2024-06-21 12:49 UTC, ufoscout requested changes

2024-06-21 12:49 UTC, ufoscout commented on src/did/src/gas.rs
> +    pub data: TransactionInput,
serde attribute `flatten` is not supported by candid. I would expect test failures. Please add explicit candid/serde/storable tests to cover the possible encoding combinations

2024-06-26 09:32 UTC, F3kilo approved these changes

2024-07-02 07:43 UTC, veeso approved these changes

2024-07-02 12:20 UTC, ufoscout requested changes

2024-07-02 12:20 UTC, ufoscout commented on src/did/src/gas.rs
> +    #[serde(default, alias = "data", skip_serializing_if = "Option::is_none")]
please add a these tests:
- serde (de)serialization roundtrip starting from a json with `data` field
- serde (de)serialization roundtrip starting from a json with `input` field
- candid (de)serialization roundtrip starting from a json with `data` field
- candid (de)serialization roundtrip starting from a json with `input` field

2024-07-08 10:22 UTC, merged