[EPROD-424] remove user registration from emvc
bitfinity-network/bitfinity-evm-sdk pull request #20
Opened 2023-07-06 14:09 UTC by itsyaasir

# Issue ticket

Issue ticket link: <>

## Checklist before requesting a review

### Code conventions

- [ ] I have performed a self-review of my code
- [ ] Every new function is documented
- [ ] Object names are auto explicative

### Security

- [ ] The PR does not break APIs backward compatibility
- [ ] The PR does not break the stable storage backward compatibility

### Testing

- [ ] Every function is properly unit tested
- [ ] I have added integration tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] IC endpoints are always tested through the `canister_call!` macro

2023-07-09 20:22 UTC, GraDKh approved these changes

2023-07-10 06:57 UTC, ufoscout approved these changes

2023-07-10 06:58 UTC, ufoscout requested changes
Is the `register-evm-agent` updated with this changes?

2023-07-10 10:37 UTC, itsyaasir commented
Should we change the naming of the crate ?

2023-07-11 14:27 UTC, ufoscout requested changes

2023-07-11 14:27 UTC, ufoscout commented on src/register-evm-agent/src/register_evm_agent/src/reservation.rs
> +            .query(&self.evmc_canister_id, METHOD_ADDRESS_RESERVED)
can this be done using the evmc-client?

2023-07-12 17:50 UTC, ufoscout commented on src/register-evm-agent/src/register_evm_agent/src/reservation.rs
> +            .query(&self.evmc_canister_id, METHOD_ADDRESS_RESERVED)
done

2023-07-12 19:05 UTC, ufoscout approved these changes

2023-07-12 19:05 UTC, merged