EPROD-1086 added validateUnconfirmedBlock permission
bitfinity-network/bitfinity-evm-sdk pull request #205
Opened 2024-11-21 14:23 UTC by veeso

2024-12-03 12:18 UTC, ufoscout requested changes

2024-12-03 12:18 UTC, ufoscout commented on src/evm-canister-client/src/client.rs
> +    pub async fn admin_enable_unsafe_blocks(
Add endpoint to check if this is enabled

2024-12-03 12:18 UTC, ufoscout commented on Cargo.toml
> +version = "0.36.1"
not needed

2024-12-16 06:56 UTC, F3kilo approved these changes

2024-12-30 09:43 UTC, ufoscout approved these changes

2024-12-31 16:04 UTC, merged