Alloy
bitfinity-network/bitfinity-evm-sdk pull request #208
Opened 2024-11-23 20:13 UTC by ufoscout

# Issue ticket

Issue ticket link: <>

## Checklist before requesting a review

### Code conventions

- [ ] I have performed a self-review of my code
- [ ] Every new function is documented
- [ ] Object names are auto explicative

### Security

- [ ] The PR does not break APIs backward compatibility
- [ ] The PR does not break the stable storage backward compatibility

### Testing

- [ ] Every function is properly unit tested
- [ ] I have added integration tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] IC endpoints are always tested through the `canister_call!` macro

2024-12-09 08:21 UTC, Maximkaaa requested changes
Just some mechanical review. I didn't actually check yet what those changes would imply for EVM or Bridges....

2024-12-09 08:21 UTC, Maximkaaa commented on src/did/src/transaction.rs
> +        // bloom.rlp_append(&mut stream);
del

2024-12-09 08:21 UTC, Maximkaaa commented on src/eth-signer/src/sign_strategy.rs
> +// }
del

2024-12-09 08:21 UTC, Maximkaaa commented on src/eth-signer/src/sign_strategy.rs
> +// }
del

2024-12-09 08:21 UTC, Maximkaaa commented on src/eth-signer/src/sign_strategy.rs
> +    // }
del

2024-12-09 08:21 UTC, Maximkaaa commented on src/eth-signer/src/transaction.rs
> +#[derive(Clone)]
Why would you delete derived traits?

2024-12-09 10:09 UTC, F3kilo approved these changes

2024-12-10 14:00 UTC, ufoscout commented on src/did/src/block.rs
> +        }
We could by creating a temporary Block wrapper that implements the RlpEncodable on itself. I am not sure it worth doing it in this case as the implemtation is pretty simple and I am not sure how the optional `base_fee` field would be managed

2024-12-10 14:01 UTC, ufoscout commented on src/did/src/block.rs
> +        // }
done

2024-12-10 14:02 UTC, ufoscout commented on src/did/src/integer.rs
> +        };
The suggested change always allocate a new String, on the contrary, the current implementation allocates only in the worst case.

2024-12-10 14:03 UTC, ufoscout commented on src/did/src/block.rs
> +    // header.hash_slow().into()
done

2024-12-10 14:03 UTC, ufoscout commented on src/did/src/integer.rs
> +        };
The suggested change always allocates a new String, on the contrary, the current implementation allocates only in the worst case.

2024-12-10 14:04 UTC, ufoscout commented on src/did/src/integer.rs
> +            U256::from_hex_str("0x18F810BD8895AA66364CBDD91A20325").unwrap()
I added a specific test for those cases

2024-12-10 14:04 UTC, ufoscout commented on src/did/src/transaction.rs
> +        // bloom.rlp_append(&mut stream);
done

2024-12-10 14:05 UTC, ufoscout commented on src/eth-signer/src/sign_strategy.rs
> +// }
done

2024-12-10 14:05 UTC, ufoscout commented on src/eth-signer/src/sign_strategy.rs
> +    // }
done

2024-12-10 14:07 UTC, ufoscout commented on src/eth-signer/src/transaction.rs
> +#[derive(Clone)]
They're wrong, there's no need for them

2024-12-11 15:17 UTC, veeso approved these changes

2024-12-12 07:06 UTC, Maximkaaa approved these changes

2024-12-12 10:23 UTC, merged