Add signature verification endpoints
bitfinity-network/bitfinity-evm-sdk pull request #209
Opened 2024-11-26 11:10 UTC by itsyaasir

# Issue ticket

Issue ticket link: <>

## Checklist before requesting a review

### Code conventions

- [x] I have performed a self-review of my code
- [x] Every new function is documented
- [x] Object names are auto explicative

### Security

- [x] The PR does not break APIs backward compatibility
- [x] The PR does not break the stable storage backward compatibility

### Testing

- [x] Every function is properly unit tested
- [x] I have added integration tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] IC endpoints are always tested through the `canister_call!` macro

2024-11-27 15:34 UTC, ufoscout requested changes

2024-11-27 15:34 UTC, ufoscout commented on src/did/src/http.rs
> +    pub url: String,
make the url `Cow<'static, str>` too

2024-11-27 15:34 UTC, ufoscout commented on src/did/src/http.rs
> +pub struct HttpResponse {
There is a duplicated definition of both the HttpRequest and HttpResponse in the `ethereum-json-rpc-client` crate, remove them and use the two here defined

2024-11-27 15:34 UTC, ufoscout commented on src/did/src/permission.rs
> +    /// Allows the caller to send transactions to the EVM
Please refine the description and maybe the name. Everyone is allowed to send transaction, so what does this permission give in addition to that?

2024-11-27 15:34 UTC, ufoscout commented on src/did/src/init.rs
> +    /// Pushing timer interval
pushing what?

2024-11-27 15:34 UTC, ufoscout commented on src/did/src/init.rs
> +    pub evm_canisters: Vec<Principal>,
What happens if more than one evm is provided? will it send the same transactions to all of them?

2024-11-28 10:51 UTC, ufoscout commented on src/did/src/init.rs
> +    pub evm_canisters: Vec<Principal>,
ok,thanks

2024-11-28 10:53 UTC, ufoscout approved these changes

2024-11-29 09:11 UTC, veeso approved these changes

2024-12-10 07:55 UTC, ufoscout requested changes

2024-12-10 07:55 UTC, ufoscout commented on src/evm-canister-client/src/client.rs
> +    pub async fn receive_transactions_unchecked(
This is to send, not to receive

2024-12-12 12:32 UTC, ufoscout commented on src/evm-canister-client/src/client.rs
> +    pub async fn receive_transactions_unchecked(
No, the client `sends` transactions, for example, the Ethereum endpoint to send a TX is indeed called **SEND**RawTransaction. If you don't like `send`, you can find a synonym like `push` or `add` but not `receive`

2024-12-24 08:53 UTC, ufoscout approved these changes

2025-03-31 06:00 UTC, Maximkaaa approved these changes

2025-04-29 10:44 UTC, merged