feat: add fee history type and helper functions for transaction
bitfinity-network/bitfinity-evm-sdk pull request #49
Opened 2023-09-20 14:42 UTC by itsyaasir

# Issue ticket

Issue ticket link: <>

## Checklist before requesting a review

### Code conventions

- [ ] I have performed a self-review of my code
- [ ] Every new function is documented
- [ ] Object names are auto explicative

### Security

- [ ] The PR does not break APIs backward compatibility
- [ ] The PR does not break the stable storage backward compatibility

### Testing

- [ ] Every function is properly unit tested
- [ ] I have added integration tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] IC endpoints are always tested through the `canister_call!` macro

2023-09-21 09:22 UTC, veeso approved these changes

2023-09-21 13:22 UTC, ufoscout requested changes

2023-09-21 13:22 UTC, ufoscout commented on src/did/src/transaction.rs
> +impl Transaction {
please add some unit tests

2023-09-22 07:56 UTC, GraDKh approved these changes

2023-09-22 09:14 UTC, ufoscout approved these changes

2023-09-22 11:57 UTC, merged