[EPROD-533] Minter types
bitfinity-network/bitfinity-evm-sdk pull request #54
Opened 2023-09-25 07:35 UTC by F3kilo

# Issue ticket

Issue ticket link:
https://infinityswap.atlassian.net/browse/EPROD-533

## Checklist before requesting a review

### Code conventions

- [X] I have performed a self-review of my code
- [X] Every new function is documented
- [X] Object names are auto explicative

### Security

- [X] The PR does not break APIs backward compatibility
- [X] The PR does not break the stable storage backward compatibility

### Testing

- [X] Every function is properly unit tested
- [X] I have added integration tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] IC endpoints are always tested through the `canister_call!` macro

2023-09-25 08:48 UTC, ufoscout requested changes

2023-09-25 08:48 UTC, ufoscout commented on src/minter-client/scripts/build_test_canister.sh
should this be integrated with the CI?

2023-09-25 08:48 UTC, ufoscout commented on src/minter-api/Cargo.toml
> +name = "minter-api"
I guess this should be called `minter-did`

2023-09-25 09:02 UTC, F3kilo commented on src/minter-client/scripts/build_test_canister.sh
Oh, it is copy/paste error. I forgot to remove this tests for another package.

2023-09-25 13:57 UTC, GraDKh approved these changes

2023-09-26 13:26 UTC, ufoscout requested changes

2023-09-26 13:26 UTC, ufoscout commented on src/minter-client/scripts/build_test_canister.sh
how is this file linked to the minter client?

2023-09-26 13:26 UTC, ufoscout commented on src/minter-client/scripts/dfx_deploy.sh
how is this file linked to the minter client?

2023-09-26 13:26 UTC, ufoscout commented on src/minter-client/scripts/download_iceth.sh
how is this file linked to the minter client?

2023-09-28 07:36 UTC, F3kilo commented on src/minter-client/scripts/build_test_canister.sh
Removed

2023-09-28 07:37 UTC, F3kilo commented on src/minter-client/scripts/dfx_deploy.sh
Removed

2023-09-28 07:37 UTC, F3kilo commented on src/minter-client/scripts/download_iceth.sh
Removed

2023-09-28 08:00 UTC, ufoscout approved these changes

2023-09-28 08:24 UTC, merged