evm-block-extractor readme and resume block extraction from latest block in zip file
bitfinity-network/bitfinity-evm-sdk pull request #90
Opened 2023-12-21 14:08 UTC by veeso

# Issue ticket

Issue ticket link: <>

## Checklist before requesting a review

### Code conventions

- [ ] I have performed a self-review of my code
- [ ] Every new function is documented
- [ ] Object names are auto explicative

### Security

- [ ] The PR does not break APIs backward compatibility
- [ ] The PR does not break the stable storage backward compatibility

### Testing

- [ ] Every function is properly unit tested
- [ ] I have added integration tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] IC endpoints are always tested through the `canister_call!` macro

2023-12-21 14:54 UTC, ufoscout requested changes

2023-12-21 14:54 UTC, ufoscout commented on src/evm-block-extractor/Cargo.toml
> +tempfile = "3"
declare the dependency version inside the top Cargo.toml file

2023-12-21 14:54 UTC, ufoscout commented on src/evm-block-extractor/src/blocks_reader.rs
> +    pub fn open(path: &Path) -> anyhow::Result<Self> {
`new`?

2023-12-21 14:54 UTC, ufoscout commented on src/evm-block-extractor/src/blocks_reader.rs
> +pub struct BlocksReader {
Add a description

2023-12-21 14:54 UTC, ufoscout commented on src/evm-block-extractor/src/blocks_reader.rs
> +    pub fn open(path: &Path) -> anyhow::Result<Self> {
Add a description

2023-12-21 14:54 UTC, ufoscout commented on src/evm-block-extractor/src/blocks_reader.rs
> +    pub fn get_last_block_number(&mut self) -> anyhow::Result<u64> {
Add a description

2023-12-21 14:54 UTC, ufoscout commented on src/evm-block-extractor/src/blocks_reader.rs
> +        let prefix = if file_name.starts_with("block") {
if it does not start with "block" then it is not a block file so it should return an error

2023-12-21 14:54 UTC, ufoscout commented on src/evm-block-extractor/src/blocks_reader.rs
> +        let prefix = if file_name.starts_with("block") {
Use constants for the PREFIX and SUFFIX and use them in both the writer and the reader

2023-12-22 04:49 UTC, itsyaasir approved these changes

2023-12-22 09:10 UTC, ufoscout approved these changes

2023-12-22 09:20 UTC, merged